#ifndef SPIKOT_CONFIG_H
#define SPIKOT_CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "Spikot"
#define TARGET_FPS 60

#define BACKGROUND_COLOR (Color){ 18, 18, 24, 255 }

#define CAT_CANVAS_SIZE 16
#define CAT_RENDER_SCALE 18.0f
#define CAT_EXPORT_SCALE 24

#define SNN_NEURON_COUNT 512
#define SNN_INPUT_NEURONS 110
#define SNN_OUTPUT_NEURONS 58
#define SNN_CONN_IN_HID 0.35f
#define SNN_CONN_IN_OUT 0.15f
#define SNN_CONN_HID_HID 0.08f
#define SNN_CONN_HID_OUT 0.35f
#define SNN_CONN_OUT_HID 0.03f
#define SNN_TIME_STEP 1.0f
#define SNN_V_REST 0.0f
#define SNN_V_RESET 0.0f
#define SNN_V_THRESHOLD 1.0f
#define SNN_TAU_MEMBRANE 5.0f
#define SNN_TRACE_DECAY 0.85f
#define SNN_STDP_POTENTIATION 0.004f
#define SNN_STDP_DEPRESSION 0.0044f
#define SNN_WEIGHT_MAX 0.45f
#define SNN_WEIGHT_INIT_MAX 0.2f
#define SNN_INHIBITORY_FRACTION 0.2f
#define SNN_INHIBITORY_GAIN 4.0f
#define SNN_REFRACTORY_TICKS 3
#define SNN_ELIGIBILITY_DECAY 0.9f
#define SNN_LEARNING_RATE 0.02f

#define WORLD_WIDTH 32
#define WORLD_HEIGHT 32
#define WORLD_FOOD_COUNT 14
#define WORLD_OBSTACLE_COUNT 48
#define WORLD_VISION_RADIUS 3
#define WORLD_TILE_PX 20

#define REWARD_FOOD 1.0f
#define REWARD_OBSTACLE -1.0f
#define REWARD_STEP 0.0f
#define HUNGER_RATE 0.004f
#define HUNGER_FOOD_RELIEF 0.4f

#define BRAIN_SUBSTEPS 12
#define BRAIN_INPUT_DRIVE 0.85f
#define BRAIN_OUTPUT_GROUP 10
#define BRAIN_HUNGER_NEURONS 4
#define BRAIN_HEARD_NEURONS 8
#define BRAIN_VOICE_NEURONS 8
#define BRAIN_EXPLORE_BASE 3.0f

#endif
