#ifndef SPIKOT_CONFIG_H
#define SPIKOT_CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "Spikot"
#define TARGET_FPS 60

#define BACKGROUND_COLOR (Color){ 18, 18, 24, 255 }

#define CAT_CANVAS_SIZE 16
#define CAT_RENDER_SCALE 18.0f
#define CAT_EXPORT_SCALE 24

#endif
