#ifndef SPIKOT_CONFIG_H
#define SPIKOT_CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "Spikot"
#define TARGET_FPS 60

#define BACKGROUND_COLOR (Color){ 18, 18, 24, 255 }

#define CAT_CANVAS_SIZE 16
#define CAT_RENDER_SCALE 18.0f
#define CAT_EXPORT_SCALE 24

#define SNN_NEURON_COUNT 512
#define SNN_CONNECTION_PROB 0.15f
#define SNN_TIME_STEP 1.0f
#define SNN_V_REST 0.0f
#define SNN_V_RESET 0.0f
#define SNN_V_THRESHOLD 1.0f
#define SNN_TAU_MEMBRANE 20.0f
#define SNN_TRACE_DECAY 0.95f
#define SNN_STDP_POTENTIATION 0.01f
#define SNN_STDP_DEPRESSION 0.012f
#define SNN_WEIGHT_MAX 1.0f
#define SNN_WEIGHT_INIT_MAX 0.08f

#endif
